### ISSUE TITLE
Locate Team Jetson TX1/2

### ISSUE THREAD

**Issue by Maciej4** [iron-claw-972/FRC2020#5]
Where is it? Does the team still own it? Answer these questions and more with this task!

**Comment by ArgyleSocks** [comment]
Jetson can't be found and was apparently stolen during the break-in a few years ago.

**Comment by ArgyleSocks** [comment]
Alternative theory is that Albert literally smeared Tabasco sauce on the Jetson and ate it with a fork and spoon (in that order).
